## Useful constants. Generated by generate_sdk_list.py

DEFAULT_VERSION = "4.3.0"

SDK_VERSION_SHA256 = {
    "4.3.0": {
        "linux_amd64": "abbea590681ba05870e5f3bc0232e021577c9ebceeb46705b7d2c2023378e981",
        "darwin_amd64": "413c8ff27fe4c6ecfbcec0b3503f64e85c69d7aaac2eef5771ef06c7a51af88b"
    },
}